import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postgres from "postgres";
import { config } from "../config.js";

const DB_URL = config.db.url;
if (!DB_URL) {
  throw new Error("DATABASE_URL environment variable is required");
}

/**
 * Custom migration runner -- intentionally NOT drizzle-orm's built-in
 * migrator.
 *
 * Why: drizzle-kit/drizzle-orm's migrator assumes it owns the full
 * lifecycle of every migration file (it generates them, hashes them, and
 * tracks that hash in its own internal table). Our initial migration
 * hand-writes partitioned-table DDL that drizzle-kit cannot generate on
 * its own (drizzle-kit has no concept of PARTITION BY RANGE), so relying
 * on the built-in migrator's hash bookkeeping for a file it never
 * generated is fragile and version-dependent. This runner instead tracks
 * "has this filename been applied" in a simple table we control, which is
 * robust to drizzle-kit internals changing across versions.
 *
 * Convention preserved from drizzle-kit: statements within a single .sql
 * file are separated by the `--> statement-breakpoint` marker, so future
 * files generated by `drizzle-kit generate` (for schema changes that
 * don't touch partitioning) can be dropped into this folder unmodified.
 */

const MIGRATIONS_TABLE = "_app_migrations";

async function ensureMigrationsTable(sql: postgres.Sql): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS ${sql(MIGRATIONS_TABLE)} (
      id SERIAL PRIMARY KEY,
      filename TEXT NOT NULL UNIQUE,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
}

async function getAppliedMigrations(sql: postgres.Sql): Promise<Set<string>> {
  const rows = await sql<{ filename: string }[]>`
    SELECT filename FROM ${sql(MIGRATIONS_TABLE)}
  `;
  return new Set(rows.map((r) => r.filename));
}

function splitStatements(fileContents: string): string[] {
  return fileContents
    .split("--> statement-breakpoint")
    .map((stmt) => stmt.trim())
    .filter((stmt) => stmt.length > 0);
}

async function applyMigrationFile(
  sql: postgres.Sql,
  filename: string,
  fileContents: string,
): Promise<void> {
  const statements = splitStatements(fileContents);
  await sql.begin(async (tx) => {
    for (const statement of statements) {
      await tx.unsafe(statement);
    }
    await tx`
      INSERT INTO ${tx(MIGRATIONS_TABLE)} (filename) VALUES (${filename})
    `;
  });
}

/**
 * The migrations directory is fixed at build time (it sits next to this
 * compiled file) -- it is never derived from request input, user input,
 * or any other untrusted source. The two fs calls below therefore trip
 * eslint-plugin-security's non-literal-fs-filename rule as a false
 * positive; suppressed with justification at each call site rather than
 * disabled globally.
 */
async function listMigrationSqlFiles(
  migrationsPath: string,
): Promise<string[]> {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- migrationsPath is derived from import.meta.url at build time, not from any external input
    const entries = await readdir(migrationsPath);
    return entries.filter((f) => f.endsWith(".sql")).sort();
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      console.log(
        "[migrate] no migrations directory found; skipping migration run",
      );
      return [];
    }
    throw err;
  }
}

/**
 * Runs all .sql files under src/db/migrations in filename order, skipping
 * any already recorded as applied. Retries the whole connect+run sequence
 * on transient failure (e.g. Postgres container still starting) --
 * waitForDatabase() in client.ts already confirms basic connectivity
 * before this runs, but that only proves Postgres accepts connections,
 * not that it's ready for DDL under concurrent startup load, so this is a
 * second line of defense.
 */
export async function runMigrations(
  maxAttempts = 5,
  delayMs = 2000,
): Promise<void> {
  const migrationsPath = fileURLToPath(
    new URL("./migrations", import.meta.url),
  );
  const sqlFiles = await listMigrationSqlFiles(migrationsPath);
  if (sqlFiles.length === 0) return;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const migrationClient = postgres(DB_URL, { max: 1 });
    try {
      await ensureMigrationsTable(migrationClient);
      const applied = await getAppliedMigrations(migrationClient);

      for (const filename of sqlFiles) {
        if (applied.has(filename)) continue;
        const filePath = path.join(migrationsPath, filename);
        // eslint-disable-next-line security/detect-non-literal-fs-filename -- filePath is built from migrationsPath (fixed, build-time) joined with a filename returned by readdir() on that same directory, not from external input
        const fileContents = await readFile(filePath, "utf-8");
        console.log(`[migrate] applying ${filename}`);
        await applyMigrationFile(migrationClient, filename, fileContents);
      }
      return;
    } catch (err) {
      console.error(`[migrate] attempt ${attempt}/${maxAttempts} failed:`, err);
      if (attempt === maxAttempts) throw err;
      await new Promise((resolve) => setTimeout(resolve, delayMs));
    } finally {
      await migrationClient.end();
    }
  }
}
